### ISSUE TITLE
Should unicode characters be escaped during the paste operation?

### ISSUE THREAD

**Issue by rigdern** [gwicksted/paste-escaped#6]
When you paste a unicode character like Ω into a TypeScript string, the paste-escaped operation doesn't escape it. Consequently, the unicode character appears to be garbled when you inspect the JavaScript string during program execution.

## Repro steps

1. Copy the following onto your clipboard: `omega: Ω`
2. Type the following code into your TypeScript file: `console.log('');`
3. Put your cursor between the single quotes and execute a paste-escaped operation. You get: `console.log('omega: Ω');`
4. Run your program.

**Unexpected result:** You see the following in the console: `omega: Î©`

**Expected result:** You see the following in the console: `omega: Ω`

## Potential fix

When you run the paste-escaped operation in step (3) it could translate the unicode character to the appropriate escape sequence for a JavaScript string. In the example above, the paste-escaped operation in step (3) would instead produce this result: `console.log('omega: \u03A9');`

**Comment by gwicksted** [comment]
It should be fine to paste as-is if the file supports that encoding (node.js, nwjs, electron environments). In other words: if it's not a webserver-served file with the default encoding (which is Latin-1) it should be ok; however, I'll look into a way to configure escaping these as well.

**Comment by gwicksted** [comment]
I chose to go beyond just Latin-1 and into all non-printable ANSI-7 as well as the control codes (minus tab). Then file encoding won't become problematic either.

* Tested with higher values such as ዿ (`\u12ff`)
* Omits tab from encoding so they're kept as-is
* Retains special handling for `\n` and `\r` escapes
* Can be disabled via a setting (`pasteEscaped.escapeNonAnsi7`) which is enabled by default

This will come in a future version (as soon as I can) of the paste-escaped extension.  I'm cramming in an update to the extension package and dependencies because a lot has changed in extension development and linting.

**Comment by gwicksted** [comment]
Version 1.4.0 published to marketplace with this feature.  Thank you for the report!
